# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       partnerspacemanager

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    patchmanager allows you to manage Sailfish OS patches
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    BSD
URL:        https://github.com/sailfishos-patches/partnerspacemanager
Source0:    %{name}-%{version}.tar.bz2
Source100:  partnerspacemanager.yaml
Requires:   %{name}-gui
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(mlite5)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10

%description
Partner-space manager allows managing the partner-space
  easily. This package contains the launcher, and QML plugin.


%package -n jolla-settings-partnerspacemanager
Summary:    Jolla settings plugin for partnerspacemanager
Group:      Qt/Qt
Requires:   %{name} = %{version}-%{release}
Provides:   %{name}-gui

%description -n jolla-settings-partnerspacemanager
Partner-space manager allows managing the partner-space
easily. This package contains the Jolla settings plugin.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%preun
# >> preun
dbus-send --system --type=method_call \
--dest=org.SfietKonstantin.patchmanager /org/SfietKonstantin/patchmanager \
org.SfietKonstantin.patchmanager.quit
# << preun

%post
# >> post
dbus-send --system --type=method_call \
--dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
# << post

%postun
# >> postun
dbus-send --system --type=method_call \
--dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
# << postun

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}-launcher
%{_libdir}/qt5/qml/org/SfietKonstantin/partnerspacemanager
# >> files
# << files

%files -n jolla-settings-partnerspacemanager
%defattr(-,root,root,-)
%{_datadir}/jolla-settings/pages/partnerspacemanager
%{_datadir}/jolla-settings/entries/partnerspacemanager.json
# >> files -n jolla-settings-partnerspacemanager
# << files -n jolla-settings-partnerspacemanager
